# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c6307954f21d32954d965806ac1ba10c"
name = "PUMA ERP"
handle = "csco-puma-new-app"
application_url = "https://bought-coordinate-craig-yes.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "greenlight-csco-puma.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,read_assigned_fulfillment_orders,read_content,read_customer_events,read_customers,read_discounts,read_discovery,read_draft_orders,read_files,read_fulfillments,read_gdpr_data_request,read_gift_cards,read_inventory,read_legal_policies,read_locales,read_locations,read_marketing_events,read_markets,read_merchant_managed_fulfillment_orders,read_online_store_navigation,read_online_store_pages,read_order_edits,read_orders,read_payment_terms,read_pixels,read_price_rules,read_product_feeds,read_product_listings,read_products,read_purchase_options,read_reports,read_resource_feedbacks,read_returns,read_script_tags,read_shipping,read_shopify_payments_accounts,read_shopify_payments_bank_accounts,read_shopify_payments_disputes,read_shopify_payments_payouts,read_themes,read_third_party_fulfillment_orders,read_translations,write_assigned_fulfillment_orders,write_content,write_customers,write_discounts,write_discovery,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_legal_policies,write_locales,write_locations,write_marketing_events,write_markets,write_merchant_managed_fulfillment_orders,write_online_store_pages,write_order_edits,write_orders,write_payment_terms,write_pixels,write_price_rules,write_product_feeds,write_product_listings,write_products,write_purchase_options,write_reports,write_resource_feedbacks,write_returns,write_script_tags,write_shipping,write_themes,write_third_party_fulfillment_orders,write_translations"

[auth]
redirect_urls = [
  "https://bought-coordinate-craig-yes.trycloudflare.com/auth/callback",
  "https://bought-coordinate-craig-yes.trycloudflare.com/auth/shopify/callback",
  "https://bought-coordinate-craig-yes.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
